env:
  global:
    # tag
    - DEPLOY_RELEASE="0.19_pre"
    #
    - FREECAD_RELEASE="0.18"
    # - DEPLOY_RELEASE=${DEPLOY_RELEASE:-$FREECAD_RELEASE}
    - OSX_PORTS_CACHE=${OSX_PORTS_CACHE:-FreeCAD/FreeCAD-ports-cache}
    - DEPLOY_REPO=${DEPLOY_REPO:-FreeCAD/FreeCAD}
    - DEPLOY=${DEPLOY:-0}

os:
  - linux
  - osx

compiler: gcc
language: cpp

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update -qq && sudo apt-get install -y desktop-file-utils jq zsync p7zip-full;
      apt-get download libc6;
      dpkg -x libc6*.deb libc6;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install jq p7zip; fi

install:
  - jq --version

script:
  - echo "Test"

after_success:
  - curl -iH "User-Agent: FreeCAD" https://api.github.com/repos/FreeCAD/FreeCAD

